### ISSUE TITLE
hide pins C18 and C19

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#101]
The IIC-Pins C18 and C19 should not be available for digital reading and writing. The onboard IIC-components will kill the values.
![grafik](https://user-images.githubusercontent.com/37311672/81300356-d65abc00-9077-11ea-822f-666fd39b1605.png)

**Comment by Amerlander** [comment]
closed by https://github.com/microsoft/pxt-calliope/pull/117
