### ISSUE TITLE
Wrong font in repository type

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#103]
The font to select the repository type differes from the rest of the gui.

![grafik](https://user-images.githubusercontent.com/37311672/81443093-05a32300-9175-11ea-93d4-1c11aab98b47.png)

**Comment by Amerlander** [comment]
What browser are you using?

Just testet in Chrome and there it looks fine:
![image](https://user-images.githubusercontent.com/3764089/81443987-ae05b700-9176-11ea-983c-232a7c625d08.png)

And how does it look in the microbit editor?

**Comment by MKleinSB** [comment]
It´s Firefox and the microbiteditor looks correct.

**Comment by Amerlander** [comment]
Nope, its nor your cache. I can confirm this for Firefox.

**Comment by Amerlander** [comment]
Firefox has dropped the support for custom fonts in selection-dropdowns. It seems like only system-fonts are applied. At the microbit editor the font in option-dropdowns is also not the same as they are using on the rest of the site., but they have a better fallback defined.

I'll add Courier and sans-serif as fallback, so it looks more similar.

**Comment by Amerlander** [comment]
closed by https://github.com/microsoft/pxt-calliope/pull/104
