### ISSUE TITLE
loading of Extensions impossible (Firefox again)

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#105]
Loading extensions in Firefox leads to this:

![grafik](https://user-images.githubusercontent.com/37311672/81499670-6f364500-92cd-11ea-9d7e-844279e6d755.png)

Using Chrome everything is fine!

**Comment by Amerlander** [comment]
Urgh!

I try to fetch the latest microbit changes in the next days. It takes some time since the DAL needs some changes before. I hope that will help, if not I'll get into this then.

**Comment by MKleinSB** [comment]
Wait fixing it. It´s in makacode microbit, too. I´ll make an issue there.

**Comment by MKleinSB** [comment]
Tested it on my other Computer. Works fine. Back again it works here too. Sorry. Can´t reproduce it.
