### ISSUE TITLE
Wrong analog Pins

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#111]
Sorry, P0 and P3 are no analog Pins!

![grafik](https://user-images.githubusercontent.com/37311672/91661354-c6aa2c00-eadb-11ea-8731-e7dbb527fd87.png)

![grafik](https://user-images.githubusercontent.com/37311672/91661386-f35e4380-eadb-11ea-8757-b09c679982df.png)

**Comment by Amerlander** [comment]
Thank you, just closed by https://github.com/microsoft/pxt-calliope/pull/110/commits/1e8e7ea57f7a88fe2478917f0c11de2585869ba9 in https://github.com/microsoft/pxt-calliope/pull/110
