### ISSUE TITLE
Search in approved extensions doesn´t work

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#128]
Searching in extensions doesn´t work as well as in makecode for microbit. It should be enough to type ds18b20 or colorbit but:

![grafik](https://user-images.githubusercontent.com/37311672/98713190-93133a00-2387-11eb-906f-5f388074617c.png)

With the correct path it works. But who knows the path for every extension?

![grafik](https://user-images.githubusercontent.com/37311672/98713340-c9e95000-2387-11eb-8ab0-c5c3507e47e5.png)

Well, it should work like the search on micro:bit.

**Comment by joernalraun** [comment]
Extensions have to be entered manually if you want them easily accessible. If you have good extensions that make sense to be included for the Calliope mini, just send them to us and we will take care of this (with the next release).

**Comment by MKleinSB** [comment]
Yes thanks, but the colorbit for example **is** in approved repos and so should appear in search!

![grafik](https://user-images.githubusercontent.com/37311672/98778680-01411680-23f3-11eb-9c08-768a97b4fbb8.png)

**Comment by joernalraun** [comment]
Oh, you are right. I didn't see it there at first.

**Comment by Amerlander** [comment]
Should be fixed in the next release
