### ISSUE TITLE
Missing possibility to set Compass

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#131]
**Describe the bug**
The possibility to set the kompass as on microbit is missing
![grafik](https://user-images.githubusercontent.com/37311672/103465111-13776b00-4d39-11eb-97ce-9cbb401677ba.png)

It would be nice to add it! (And loudness, too :-)

**Comment by Amerlander** [comment]
Targeted in https://github.com/microsoft/pxt-calliope/pull/147
