### ISSUE TITLE
On Pin pressed doesn´t work as expected

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#134]
Using pin pressed and pin released doesn´t work as expected most of the time even with wet fingers. (not available in simulator)
![grafik](https://user-images.githubusercontent.com/37311672/115138222-2e8d9280-a02b-11eb-9159-4c547a7890da.png)
The LED should light red when P0 and GND is connected, otherwise blue. But it only works randomly.

**Comment by MKleinSB** [comment]
Ah, it was this one. https://github.com/microsoft/pxt-microbit/issues/963

**Comment by Amerlander** [comment]
Targeted in https://github.com/microsoft/pxt-calliope/pull/147

**Comment by MKleinSB** [comment]
Yes, works as expected now!
