### ISSUE TITLE
Shrinking expandable Arguments kills them

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#137]
Expandle Arguments don´t work, even in playground. They need to be fully expanded or they generate an error of missing Arguments. 
![grafik](https://user-images.githubusercontent.com/37311672/115159956-0dae5700-a096-11eb-9738-2fc0f5aec87e.png)

switching to Javascript shows that the arguments are missing

![grafik](https://user-images.githubusercontent.com/37311672/115159978-1e5ecd00-a096-11eb-9008-4842305a0512.png)

same on micro:bit https://github.com/microsoft/pxt-microbit/issues/3986

**Comment by Amerlander** [comment]
I commented in the micro:bit issue with a solution on this. Are there any expandable blocks in the editor itself which are causing this issue or is it only that sample in the playground?

**Comment by MKleinSB** [comment]
Thanks that works now for me!
In the Editor itself there are no expandable Blocks. Should we close this issue?
![grafik](https://user-images.githubusercontent.com/37311672/115225701-ac769a00-a10e-11eb-8b6d-8688f1fc84c6.png)

**Comment by Amerlander** [comment]
I think, Its not an issue in this repo, but a misleading sample in the playground which has to be fixed - but the playground is independent of this repo.
