### ISSUE TITLE
setpitchpin still not working

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#145]
https://github.com/microsoft/pxt-calliope/issues/113

For the work with children it is much easier to use two crocodileclips on Ground and Pin P1 instead of connecting the motorpin to a speaker. 
When will there be an update to handel the sound of the calliope mini like the microbit does this?

Thx  Michael

**Comment by tianchrist** [comment]
I know this is two years old but it may still help people who find this thread.
I found the following code in the docs that works with my Calliope in MakeCode. This code will output the sound on P1 just like with the micro:bit. So you can use crocodile clips. The on-board speaker will not ouput sound, however.

```
pins.setAudioPin(AnalogPin.P1)
pins.analogPitch(440, 1000)
```

**Comment by MKleinSB** [comment]
Ja, aber die Musikblöcke sollten auch funktionieren.
