### ISSUE TITLE
Choosing RAM size does not work

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-calliope#161]
We have implemented a setting to choose between 16 and 32kb Target. But regardless of what switch is on, the hex file is always compiled with the settings for 32kb RAM.

Is it even possible to change the Ram size in that way? Are there better options, like choosing a device every time a new project is created as we see it in https://maker.makecode.com?

![image](https://user-images.githubusercontent.com/3764089/159899997-83ebd07a-6f79-451a-8d2c-6e5809d39cd5.png)

```json
"userConfigs": [
            {
                "description": "32K RAM (mini v2 and some v1.3)",
                "config": {
                    "microbit-dal": {
                        "stack_size": 2048,
                        "sram_end": "0x20008000"
                    },
                    "RAM_SIZE": "\"32K\""
                }
            },
            {
                "description": "16K RAM (mini v1.3 and below)",
                "config": {
                    "microbit-dal": {
                        "stack_size": 1280,
                        "sram_end": "0x20004000"
                    },
                    "RAM_SIZE": "\"16K\""
                }
            }
        ]
```

**Comment by Amerlander** [comment]
@pelikhan, can you (or can you name us someone who can) assist us regarding this issue?

**Comment by pelikhan** [comment]
This should work since it is the mechanism to enable/disable BLE as well.

I think you need to make sure those RAM_SIZE is mapped to a constant that starts with ``YOTTA_CFG_``. See https://github.com/lancaster-university/microbit-dal/blob/602153e9199c28c08fd2561ce7b43bf64e9e7394/inc/platform/yotta_cfg_mappings.h#L23.

If you add ?dbg=1 or build locally, you should see all the generated build files and in particular the constants that are generated by pxt.

Best to reach out for the MakeCode team.

**Comment by Amerlander** [comment]
well, when I add `?dbk=1` the Parameter in `yotta.json` is always `32K` no matter what I choose in the setting.

Also when I build it locally it is always the value which is default in `optionalConfig`. When I change the defaults to `16K` the build process builds the 16k version as expected.

https://makecode.calliope.cc/app/f3b8cb87d8c932e5673206a3808d227e36964416-1e24dc8c20?dbg=1#editor

![image](https://user-images.githubusercontent.com/3764089/161079227-a78fa9e2-2a0d-458c-b3bc-d8c68b82d40d.png)
![image](https://user-images.githubusercontent.com/3764089/161079352-d26b5406-8a8a-4124-b5de-a0dc1fcb9e58.png)

**Comment by pelikhan** [comment]
Try using yotta instead of build config
________________________________

**Comment by Amerlander** [comment]
Can you elaborate on this, aren't we already using yotta?

**Comment by Amerlander** [comment]
ok, I see we have some settings in [/bluetooth/pxt.json](https://github.com/microsoft/pxt-calliope/blob/ec378c5b09bffd04bfc55fb4198304688c8bb861/libs/bluetooth/pxt.json#L20) and some in [/core/pxt.json](https://github.com/microsoft/pxt-calliope/blob/ec378c5b09bffd04bfc55fb4198304688c8bb861/libs/core/pxt.json#L105), so it might interfere there. Everything is already in yotta.

I`ll test this local and come back with a PR or more questions :) thank your for your help!

**Comment by Amerlander** [comment]
I did some more testing:

- Change from 32K to 16K per switch and click `save` does not change the hex
- Changing from 32K to 16K per switch, click `save` and click on the button `edit settings in text mode` changes the hex as expected – even if  I do not change anything in text mode. But I have to download the hex file while the text mode is active, if I switch back to the blocks view before downloading the hex file it does not apply the settings to the hex file.

**Comment by Amerlander** [comment]
Having it on https://makecode.calliope.cc/beta it now seems to be a bit better and does not need to recompile every time it switches to 32K. But still sometimes caches the old setting. So switching from 16K to 32K or from 32K back to 16K works in general, but not every time and is a bit laggy and not really predictable.

**Comment by Amerlander** [comment]
@pelikhan this issue still persist.

Being in blocks-mode MakeCode always delivers a hex file with the default settings, no matter what setting is selected. Switching to JS mode delivers a hex file with the selected settings.

A hex file for 32K is about 8-10kb bigger than a hex file for the 16K device.

## To reproduce

1. Open https://makecode.calliope.cc/beta
2. Open a new project
3. set a simple program, like showing a Hearth on start.
4. Open project settings and choose "32K RAM"
5. Click on save, editor goes back to blocks
6. Download file, notice, that the file size is now 653.08 KB
7. Switch to JS Mode
8. Download again, notice, that the file size is now 661.48 KB

- Both files should be the same size and run only on a calliope mini with 32K RAM. 
- The first file will run on all Calliope mini devices
- The second file will only run on Calliope mini devices having 32K RAM.

**Comment by Amerlander** [comment]
@riknoll could you look into this?

> Being in blocks-mode MakeCode always delivers a hex file with the default settings, no matter what setting is selected. Switching to JS mode delivers a hex file with the selected settings.
> 
> A hex file for 32K is about 8-10kb bigger than a hex file for the 16K device.
> 
> ## To reproduce
> 1. Open https://makecode.calliope.cc/beta
> 2. Open a new project
> 3. set a simple program, like showing a Hearth on start.
> 4. Open project settings and choose "32K RAM"
> 5. Click on save, editor goes back to blocks
> 6. Download file, notice, that the file size is 653.08 KB
> 7. Switch to JS Mode
> 8. Download again, notice, that the file size is now 661.48 KB
> 
> * Both files should be the same size and run only on a calliope mini with 32K RAM.
> * The first file will run on all Calliope mini devices
> * The second file will only run on Calliope mini devices having 32K RAM.

**Comment by joernalraun** [comment]
Doing a manual a reload after changing the settings works.
If it would be possible to do an automatic reload after clicking "Save" it might be a quick fix to make it work.
