### ISSUE TITLE
endless compiling of neopixel extension

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#171]
the neopixel extension is compiling endless!

![grafik](https://user-images.githubusercontent.com/37311672/160889554-2a510154-a847-468b-b56d-3b721ed5da67.png)

**Comment by MKleinSB** [comment]
The problem seemes to be in https://github.com/microsoft/pxt-ws2812b

**Comment by Amerlander** [comment]
I have no issues adding neopixel or [microsoft/pxt-ws2812b](https://github.com/microsoft/pxt-ws2812b) and downloading a hex file. Can you try to provide a step-by-step guide to get this issue?

**Comment by MKleinSB** [comment]
Just tested again and it works. Perhaps a browserproblem. Sometimes i run makecode for microbit and calliope parallel. 
Thanks for looking at it!
