### ISSUE TITLE
Tutorials stopped working in v3.0.33

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-calliope#178]
Tutorials stopped working in the stable Version(v3.0.33). 

They either do not appear at all, or they are shown, but can't be opened.

**To Reproduce**
1. Clear cache or use an incognito browser session
2.  Go to https://makecode.calliope.cc
3a. No tutorials or links are shown
3b. The tutorials are showing up, but they can not be opened.

**Expected behavior**
Tutorials should be visible and open.

**Screenshots**
![image](https://user-images.githubusercontent.com/3764089/162697393-f325bb13-fdef-45de-9924-94c29813eff9.png)

![image](https://user-images.githubusercontent.com/3764089/162697329-0eea45ca-921e-41b0-b4f0-5d84699cac77.png)

**Comment by Amerlander** [comment]
@riknoll this is affecting the stable version. Can this be caused by our latest updates?

**Comment by riknoll** [comment]
Yes, this was a result of changing the major version to 4. I created a v3 branch in the repo that points to the pre-v4 changes and this should be fixed now

**Comment by Amerlander** [comment]
yes, seems fixed now.
