### ISSUE TITLE
Bump new Version to https://makecode.calliope.cc/beta

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-calliope#182]
@riknoll What can we do to get the latest version available on [makecode.calliope.cc/beta](https://makecode.calliope.cc/beta) ?

**Comment by Amerlander** [comment]
@pelikhan, may I ask you instead?

**Comment by abchatra** [comment]
Sorry for the delay. I will take a look this week.

**Comment by Amerlander** [comment]
Great, thank you! If we have to do any changes, please just let me know. :)

**Comment by abchatra** [comment]
I am still investigating. For now you can use this link to test /beta
https://makecode.calliope.cc/app/86269a2e380bebba51c578b1f0eb9fec59704f31-e497f7dde5

**Comment by Amerlander** [comment]
Thank you for looking into this @abchatra. 
The link seems to be the state of tag v4.0.19, actually I was hoping to get a new release (then v4.0.20), which should be based on the latest changes in master.

Additionally, I mentioned it before, but it might have been overseen: on my local setup I had to cherry-pick the changes made in https://github.com/microsoft/pxt/pull/8669 to pxt 7.0.x, since afaik they are only made to pxt v7.4.x and above, but not downgraded to our currently used version which is v7.0.16. I hope that's not the reason for our issues in getting it deployed.

**Comment by abchatra** [comment]
This one should v4.0.20 https://makecode.calliope.cc/app/50166e7843ec9d4c8c68e057a77890cbbc6f15df-2ef1cfedc9

I am still working on the other issue.

**Comment by abchatra** [comment]
Done /beta should point to the latest now.
