### ISSUE TITLE
Makecode blocks for analog write and analog read 

### ISSUE THREAD

**Issue by fabianhugo** [microsoft/pxt-calliope#209]
To the best of my knowledge, the all digital pins should be able to generate a PWM signal (analog write, see [tech](https://tech.microbit.org/hardware/edgeconnector/#pins-and-signals)) so within the "Pins" group of makecode, whenever choosing a **analog write** block all pins should be available. While when using the **analog read** block only the analog input pins should be available. I don't know if that doesn't concern other blocks of different groups as well. 
So the "Analog" pins are actually referring to analog input pins only. 

EDIT: Servo pins are affected as well, since they are driven by a PWM signal. 
And the microphone should not be available for analog write I think.

**Comment by Amerlander** [comment]
All pins are made available now, but write only pins include "write only" in their name.
