### ISSUE TITLE
Link to tos ist broken in German

### ISSUE THREAD

**Issue by joernalraun** [microsoft/pxt-calliope#21]
When using German as main language the link to tos is https://www.microsoft.com/de-de/corporate/rechtliche-hinweise/nutzungsbedingungen.aspx though it seems like the following url should be the right one:
https://www.microsoft.com/de-de/rechtliche-hinweise/nutzungsbedingungen

**Comment by abchatra** [comment]
@joernalraun I need your help in testing this. There is a potential fix deployed for privacy URL redirect. Can you see if that fixes the issue?

**Comment by joernalraun** [comment]
@abchatra unfortunately I can't see a difference.

**Comment by Amerlander** [comment]
seems fixed now
