### ISSUE TITLE
Translation appears different

### ISSUE THREAD

**Issue by joernalraun** [microsoft/pxt-calliope#22]
When opening German version of MakeCode within a WebView of an App (on iOS) I see the string „show leds“ in German. However, when directly surfing to it on the same device and same language settings the English version is displayed.
On a desktop, if I have a session open for a very long time I see the blocks „on Pin pressed“ in German as well, but when refreshing the page it is displayed in English!

**Comment by Amerlander** [comment]
I think this can be closed now
