### ISSUE TITLE
No WebUSB-pairing when V1 or V2 is chosen

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#238]
There is no WebUSB-functionality when calliope V1 or V2 is chosen in makecode **V6.0.22**. When V3 is chosenit works perfectly with V1, V2 and V3. 

![grafik](https://github.com/microsoft/pxt-calliope/assets/37311672/e4dcf38b-5d42-4813-87e1-634d42147d55)

**Comment by joernalraun** [comment]
Right now, there are some issues with WebUSB for older devices. We are trying to fix this and open it for all other hardware as well.

**Comment by Amerlander** [comment]
I created seperate issues for webUSB:

For Calliope mini 2: https://github.com/microsoft/pxt-calliope/issues/248

For enabling support for Calliope mini 1 while mini 2 is not suporting it: https://github.com/microsoft/pxt-calliope/issues/250

WebUSB will be disabled for mini 1 and 2 in the next version until these issues are not closed. But it will be possible to enable webUSB for all devices by adding `?usb` to the url. Still makecode wont be able to connect to the mini 2.
