### ISSUE TITLE
RGB Pin choosable in Blocks of Neopixel Library 

### ISSUE THREAD

**Issue by fabianhugo** [microsoft/pxt-calliope#243]
The blocks of the Neopixel library include more control possibilities for the neopixel and thus make cool effects possible. If the internal RGB pin is also selectable here, the extended control options can be used for the 3 internal RGB leds.

**Comment by Amerlander** [comment]
![image](https://github.com/microsoft/pxt-calliope/assets/3764089/988a7a2c-379a-4d19-be7d-95e34189844a)
