### ISSUE TITLE
Set Audio Pin block missing

### ISSUE THREAD

**Issue by fabianhugo** [microsoft/pxt-calliope#244]
The calliope mini 3 can switch its internal speaker off to redirect the audio signal to one of the pins of the header. The default pin is p0, but it is actually choosable with this block: 
![grafik](https://github.com/microsoft/pxt-calliope/assets/32654742/4c89e3a6-563d-428d-bc1e-af1d47e1ebc8)
This block is still missing in the alpha.

**Comment by Amerlander** [comment]
Made them available for all devices, but I think they wont work on mini 1 and 2
