### ISSUE TITLE
Servos again...

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#245]
Afaik Servos can be controlled from digitalpins, so it would be nice to have A1_RX as Servopin for use with the calliope mini Servoboard
https://www.hackster.io/MKlein/servoboard-fur-den-calliope-mini-6fb045

![grafik](https://github.com/microsoft/pxt-calliope/assets/37311672/c274c6e2-4e2b-41ff-a499-0403d0b6dc5c)

**Comment by Amerlander** [comment]
Will be included in the next update

![image](https://github.com/microsoft/pxt-calliope/assets/3764089/4fb218b7-181b-4c86-aa01-10276d4a586e)
