### ISSUE TITLE
Behavior of Button in Simulator inconsistent

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#249]
Button A or B in simulator only works if you hit exactly the "metal part" (1) and not the button (2). Should work with both as in V1/V2 Simulator.

![grafik](https://github.com/microsoft/pxt-calliope/assets/37311672/c2bf4245-5423-43d8-bc07-ddb46448ac81)

**Comment by Amerlander** [comment]
Thank you, its already on my list... the svg and labels are still work in progress.
