### ISSUE TITLE
digital read doesnt work in simulation

### ISSUE THREAD

**Issue by ToniTaste** [microsoft/pxt-calliope#260]
Digital Read doesn't work in the simulation. 

**To Reproduce**
Please use this program:
basic.forever(function () {
    if (pins.digitalReadPin(DigitalPin.P0) == 0) {
        basic.setLedColor(0xff0000)
    } else {
        basic.setLedColor(0x00ff00)
    }
})

**Expected behavior**
When you set pin P0 to 1 in the simulation there won't be a change on the light color. 

**Screenshots**
![Screenshot 2023-11-21 124139](https://github.com/microsoft/pxt-calliope/assets/8844571/21f97653-801b-46c1-b3a2-2557236e1b3d)

**Desktop (please complete the following information):**
 - OS: Win10H22
 - Browser Chrome 119

**Comment by Amerlander** [comment]
Thank you for finding that issue. 

Will be fixed in https://github.com/microsoft/pxt-calliope/pull/261
