### ISSUE TITLE
Missing String for translation of "is compass calibrated" (or should be hidden)

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#262]
The string for translation of "is compass calibrated" is missing.
Perhaps it is not longe needed as in makecode for microbit. So you should deprecate it. 
![grafik](https://github.com/microsoft/pxt-calliope/assets/37311672/4841e5ce-f893-4526-8639-0303bb0f5a70)

**Comment by Amerlander** [comment]
Just tested the block, and it even did not work - It's always `false`. So I'll deprecate it.

I liked the block, but its use cases might be rare. When the program should run and only use the compass if it was already calibrated, it is good to have:

![image](https://github.com/microsoft/pxt-calliope/assets/3764089/eb459825-5b58-4d0d-89d3-f3af3410f01f)
