### ISSUE TITLE
Simulatorerrors in 6.0.26 Calliope V1

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#266]
Noch 2 Fehler im Simulator sind mir heute vor der Klasse aufgefallen:

1. Geschwindigkeit bei schreibe Text
 
![grafik](https://github.com/microsoft/pxt-calliope/assets/37311672/002ddc2a-164c-45e0-9d02-4d983bf8af3c)
geht, 
![grafik](https://github.com/microsoft/pxt-calliope/assets/37311672/cd65d984-2c1a-43ad-a128-34e2f6a36bae)
zusammengeklappt ist wieder lahm

2. **Wenn geschüttelt** funktioniert nicht im Simulator

**Comment by Amerlander** [comment]
Gerade getestet, ist sogar in den alten Versionen schon so.
