### ISSUE TITLE
Projects issues

### ISSUE THREAD

**Issue by joernalraun** [microsoft/pxt-calliope#274]
Within three projects (mini-Chat, Rock-Paper-Scissors and Multidice) on the main page are some options wrong or not completely available.
The mini-Chat project has no radio blocks to choose from and on Multidice it stops after the second screen and jumps to a complete one.
Rock-Paper-Scissors needs block from the Logic section, but that is also not available.

**Comment by Amerlander** [comment]
- [ ] mini-Chat project has no radio blocks to choose from 
- [ ] Multidice it stops after the second screen and jumps to a complete one.
- [ ] Rock-Paper-Scissors needs block from the Logic section
