### ISSUE TITLE
pxt-neopixel library doesn´t work  any more (only)  on CalliopeMini

### ISSUE THREAD

**Issue by MKleinSB** [Microsoft/pxt-calliope#29]
We have Problems using the neopixel library because of missing math functions. 
As a workaround we have to add

// notwendige Funktionen für das aktuelle Neopixel-Paket
namespace Math {
export function idiv(x: number, y: number) { return x / y }
export function round(x: number) { return x }
}

So I think we need this two functions in makecode ;-)

![1](https://user-images.githubusercontent.com/37311672/43923035-dada8fb4-9c20-11e8-82d8-226249411395.png)

**Comment by pelikhan** [comment]
@thinkberg are you integrating updates to pxt-microbit#master to this repo?

**Comment by pelikhan** [comment]
This issue is fixed in 1.0.25.
