### ISSUE TITLE
Simulator not triggering events in latest chromium based browsers

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-calliope#296]
**Description:**
After the update to Microsoft Edge Version 125.0.2535.79 and Google Chrome Version 125.0.6422.142, the simulator in MakeCode no longer triggers events when buttons or pins are interacted with. The inputs seem clickable, but does not react visually on click. This issue does not occur in other browsers or older versions of Edge and Chrome.

**Steps to Reproduce:**
1. Open MakeCode on a Windows 10 or 11 machine with Edge Version 125.0.2535.79 or Chrome Version 125.0.6422.142.
2. Create a simple program with events such as "when button A is pressed" or "when pin 0 is touched".
3. Run the simulator and try interacting with the buttons or pins.

**Expected Behavior:**
The simulator should react on interaction and execute the code within the event blocks when buttons or pins are interacted with.

**Actual Behavior:**
The simulator does not react on clicks and does not execute the code within the event blocks.

**Additional Information:**
- The issue is present with the latest MakeCode version and also with version 4.
- The issue does not occur in Safari on iPad, in the Edge app with version 125.0.2535.72, or on Windows 8 with the old Edge.
- makecode.microbit.org seems to work correctly in the current Edge version.
- The issue was confirmed by other users who also reported that no button events are triggered and no analog values can be input at the pins.
- The problem is not reproducible when the editor is started with `pxt serve` or hosted locally with `statickpkg`.
- There are no errors in the JavaScript console, making it difficult to debug the issue without guessing.

**Forum Discussion (german):**
- [Edge Version 125.0.2535.79 = Simulator kaputt?](https://forum.calliope.cc/t/edge-version-125-0-2535-79-simulator-kaputt/2903/4)

**System Information:**
- **Browser:** 
  - Microsoft Edge Version 125.0.2535.79
  - Google Chrome Version 125.0.6422.142
  - Other Chromium based browsers like Opera and Vivaldi on latest Versions
- **Operating System:** Windows 10 and Windows 11
- **MakeCode Version:** Latest and v4

**Notes:**
- the issue resolves when a sensor is read, for example, writing light intensity to a variable or displaying it on the screen.

**Comment by Amerlander** [comment]
@abchatra I'm stuck on this issue. I don't really have any idea how to debug it. Do you know why the simulator behaves differently on the hosted version compared to my development environment?

**Comment by abchatra** [comment]
@riknoll ?

**Comment by riknoll** [comment]
will take a look today!

**Comment by riknoll** [comment]
I'm able to repro this locally, seeing the same behavior as @Amerlander where it doesn't repro when serving from the cli. I also have confirmed that this isn't a case of one event listener preventing propagation to another; it seems like the browser is genuinely not firing the events on the hosted site.

Kind of stumped as to what to do here, but at least I can reproduce it easily. I'll try a few things and see if any of them happen to fix things. Will update when I have more info.
