### ISSUE TITLE
Error in bluetooth  package

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#38]
Using the Event bluetooth.OnUartDatareceived I get an Error
![1](https://user-images.githubusercontent.com/37311672/49471622-ae758200-f80d-11e8-900b-758003f3a3f3.png)

**Comment by MarkusPiotrowski** [comment]
I got the same error but the block seems to work in my case.

**Comment by MKleinSB** [comment]
Yes, it´s only an error in the simulator.
P.S. You can test the V1 Core at fold-lab.com
