### ISSUE TITLE
Wrong analog Pin in Javascript mode

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#43]
In Javascript Mode the preset Pin P0 isn´t an analog Pin at the Calliope Mini. Please use P1. Only ServoSetpulse is correct.
![Unbenannt](https://user-images.githubusercontent.com/37311672/56093283-a7026b80-5ec6-11e9-8f40-fdc8c98f4479.png)

**Comment by MKleinSB** [comment]
Error still exists in new version

![1](https://user-images.githubusercontent.com/37311672/70631159-07e86c00-1c2d-11ea-9320-8bb2cd957e38.png)

**Comment by Amerlander** [comment]
Closed in https://github.com/microsoft/pxt-calliope/pull/62
