### ISSUE TITLE
Pins mapped wrong in Simulator

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#44]
The Pins P0, P1, P2, P3 should be marked when high and the analog/digital values should be displayed at the correct place. ( The other pins on the Expansion-port should be marked, too when they are used)
![Unbenannt](https://user-images.githubusercontent.com/37311672/56093426-05304e00-5ec9-11e9-9103-c7611d2992b3.png)

**Comment by MKleinSB** [comment]
@Amerlander Motorpins should be marked too when using the motorblocks and perhaps rotating wheels beneath the calliope like openroberta does?

**Comment by Amerlander** [comment]
the 6th motorpin is now also included in the PR https://github.com/microsoft/pxt-calliope/pull/72.
The leftover things will follow these days.

**Comment by Amerlander** [comment]
The Pins P0 to P3 are now fixed. The positions are corrected and they are displaying the analog as well as the digital values.
I also added the black circle in the middle of the little pins to the hovering are, so it is a bit easier to hover them with the mouse.

**Comment by Amerlander** [comment]
Since we will replace the whole simulator illustration with the actual layout I didn't put too much effort into the visual aspect yet.

**Comment by MKleinSB** [comment]
Works great now! Only the unused labels look a little bit funny ;-)
![Unbenannt](https://user-images.githubusercontent.com/37311672/72978283-772db000-3dd6-11ea-989e-2bc8c11e062f.png)

**Comment by Amerlander** [comment]
The unused labels will get removed again, they were just for debugging there
