### ISSUE TITLE
Umlaute do not work

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#46]
When you change those blocks to Javascript

![Unbenannt2](https://user-images.githubusercontent.com/37311672/57199364-65715780-6f7e-11e9-8456-174f7013ef65.png)

... and change something in Javascript. (add a return)
and change back to Blocks you get errors:

![Unbenannt](https://user-images.githubusercontent.com/37311672/57199358-5ee2e000-6f7e-11e9-98b7-b51dbba4226e.png)

**Comment by Amerlander** [comment]
fixed with https://github.com/microsoft/pxt-calliope/pull/54
