### ISSUE TITLE
What is a workaround to have a working web version same as makecode.calliope.cc?

### ISSUE THREAD

**Issue by baradaran** [microsoft/pxt-calliope#47]
staticpkg problem still persists [microsoft/pxt-calliope#31]

However there is already a working version hosted here from Microsoft : 
https://makecode.calliope.cc/ 
How is this possible? is there a way to manually have a short fix for the old version? 

Thank you for your time

**Comment by baradaran** [comment]
@pelikhan  It would be great if you could answer this.

**Comment by pelikhan** [comment]
staticpkg is not supported on the pxt version calliope is built against. It needs to be upgraded.

**Comment by magicmarvman** [comment]
@pelikhan @joernalraun 

Are there any plans or schedules to upgrade the version? This would be great, also for me it would be a nice feature...

Apart from that, this repo hasn't been updated for a year.... Are people still working on this MakeCode®?

**Comment by Amerlander** [comment]
@magicmarvman we just started a pull request for a new version. It will still be beta, but most things work well.

So work on this MakeCode wasn't that much the last time, but it will get more now.

**Comment by Amerlander** [comment]
fixed with https://github.com/microsoft/pxt-calliope/pull/54
