### ISSUE TITLE
No block to turn off RGB Led

### ISSUE THREAD

**Issue by Moritzheine** [microsoft/pxt-calliope#49]
There is no block to turn off the RGB led. Turning it off using the '0' from the 'maths' menu is very counter intuitive.

**Comment by MKleinSB** [comment]
Yes, we need the color black like in the Neopixel Extension.
![Unbenannt](https://user-images.githubusercontent.com/37311672/58489297-44f68080-816b-11e9-8367-15ef7ffbed7e.png)
Argh! Another bad german translation. Large or not?

**Comment by baradaran** [comment]
It also turns off by leaving color section empty (which is a challenge if you are working with blocks by itself!)

**Comment by Amerlander** [comment]
fixed with https://github.com/microsoft/pxt-calliope/pull/54
