### ISSUE TITLE
Missing pins for rx and tx

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#55]
The pins C16 and C17 don´t  appear for serial connections!
So I can´t use and update my ESP-Extension
![1](https://user-images.githubusercontent.com/37311672/70626933-9822b300-1c25-11ea-98e5-98c09e39806a.png)

**Comment by MKleinSB** [comment]
bitte serial.cpp enum serialpin ändern.

**Comment by Amerlander** [comment]
C16 and C17 are now there for serial Connections, but USB_TX and USB_RX might not working yet and still needs to be fixed.
