### ISSUE TITLE
Can´t load Extensions without being logged in at Github

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#56]
You still need to be logged in at Github if you want to load an extension.
Tutorials using extensions don´t work, too.

![1](https://user-images.githubusercontent.com/37311672/70628173-f3ee3b80-1c27-11ea-9c54-2cd93661d8f5.png)

**Comment by Amerlander** [comment]
Should now work in https://makecode.calliope.cc/beta
