### ISSUE TITLE
You can´t login to github

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#59]
it is impossible to login into Github with the updated Version.

**Comment by Amerlander** [comment]
The oAuth-Login seems only to work for approved Domains and localhost. So we have to disable it when its hosted elsewhere. In the meanwhile you can use manuallly the token method:

![1](https://user-images.githubusercontent.com/3764089/71025397-3e2f5b00-2107-11ea-8612-31546ad482ec.gif)

**Comment by pelikhan** [comment]
We should be able to have it working on makecode.calliope.cc

**Comment by pelikhan** [comment]
SHould be fixed in the latest build.
