### ISSUE TITLE
Shouldn´t P3 be analogpin or pwmpin?

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#61]
@Amerlander :  In pinscompat.ts shouldn´t P3 better be PWM instead of AnalogPin?

**Comment by Amerlander** [comment]
Right, P0 and P3 are digital and therefore PWM should be right. P1 and P2 are Analog. Thank you.

Fixed in https://github.com/microsoft/pxt-calliope/pull/62
