### ISSUE TITLE
Missing function turnrgbledoff in Simulator

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#63]
I think you forgot implementation of turnrgbledoff in the simulator:
![1](https://user-images.githubusercontent.com/37311672/71305646-6f45af00-23d7-11ea-8bf1-c2f42f9f9a1d.png)
Or you remove it, it´s not necessary.

**Comment by Amerlander** [comment]
fixed by https://github.com/microsoft/pxt-calliope/pull/69

**Comment by MKleinSB** [comment]
@Amerlander Error still exists in V2.1.39

**Comment by Amerlander** [comment]
V2.1.39 is older than https://github.com/microsoft/pxt-calliope/pull/69. So it will be in the next release.

**Comment by Amerlander** [comment]
Die Texte sind vom Micro:bit, die Übersetzungen müssen aber wohl von Hand in bei Calliope übernommen werden.
