### ISSUE TITLE
Menus  Reference and Hardware don´t exist

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#65]
Menu Reference and menu Hardware don´t exist.
![5](https://user-images.githubusercontent.com/37311672/71646343-48488080-2ce7-11ea-96e1-01f0cd7ec366.png)

**Comment by joernalraun** [comment]
This is by intention. There are a couple of translation issues within this topics that won't be fixed soon. Once we have the content available we will integrate both again.

**Comment by Amerlander** [comment]
I just updated the docs menu and files. For german, we have to still add the translation to /about.md to show up. That has to be done after release, since crowdin isn't set up to translate the files on the /beta.
