### ISSUE TITLE
Leading characters in German Strings not capitalized correct 

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#66]
I thought it was a hosting-problem of makecodebeta.calliope.cc,  but then I found the bug in the other makecode editors. Somewhere in the latest makecode or pxt-updates the capitalization was killed:

https://github.com/microsoft/pxt-arcade/issues/1691

**Comment by Amerlander** [comment]
yes, I think its something which has to be changed in PXT itself.

The behavior seems for me a bit unpredictable:

Original string is not lower cased:
![grafik](https://user-images.githubusercontent.com/3764089/72108305-9129b600-3333-11ea-9856-9540bfada2e5.png)

Translated string is lower cased, regardless of crowdin translation:
![grafik](https://user-images.githubusercontent.com/3764089/72108335-a30b5900-3333-11ea-87cf-69dc75555be0.png)

Most strings are not lower cased:
![grafik](https://user-images.githubusercontent.com/3764089/72108397-c8986280-3333-11ea-9ce1-18e98f7dc4d6.png)

At MicroBit there is also no lower casing:
![grafik](https://user-images.githubusercontent.com/3764089/72108553-30e74400-3334-11ea-98f6-932dce910fe6.png)

**Comment by MKleinSB** [comment]
The lower casing is the same in https://makecode.microbit.org/beta which has the same pxt version like Calliope mini

![minibeta](https://user-images.githubusercontent.com/37311672/72113266-3b0f3f80-3340-11ea-8044-a0baafacb1f1.png)

**Comment by pelikhan** [comment]
I will look into this

**Comment by Amerlander** [comment]
fixed in pxt: https://github.com/microsoft/pxt/pull/6444
