### ISSUE TITLE
Beta Hosting

### ISSUE THREAD

**Issue by Amerlander** [microsoft/pxt-calliope#67]
The newest releases are not available at https://makecode.calliope.cc/beta as I would expect.

The `beta.ref` file exists and has ` "appref": "v"`, so I thought every release should get deployed on the website as beta.

Since there are a Issues like https://github.com/microsoft/pxt-calliope/issues/59 and https://github.com/microsoft/pxt-calliope/issues/57 which seem to interfere with the hosting it would be great, if we would have the newest releases on the Microsoft hosting as beta.

**Comment by pelikhan** [comment]
Now latest is live with capitalization fix. Also migrated to github actions.
