### ISSUE TITLE
Missing pictures in tutorial, first steps ...

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#70]
The cards in First steps, Tutorial ... stay blank since the new hosting of calliope beta! 
![Unbenannt](https://user-images.githubusercontent.com/37311672/72627964-ac0cb380-394d-11ea-9276-e7efc6936752.png)

**Comment by pelikhan** [comment]
You have “/docs/“ added to all your images.

**Comment by Amerlander** [comment]
Fixed them now.

On our test server the doc images wasn't rendered without this addition, but since local-http server also doesn't need that it has to be a wrong configuration on that server.

**Comment by MKleinSB** [comment]
@Amerlander : Pictures in Tutorials work, but not those when klicking the Cards!
![Unbenannt](https://user-images.githubusercontent.com/37311672/72977777-7e07f300-3dd5-11ea-8221-8b0f0b2ecef9.png)
