### ISSUE TITLE
Missing and outdated extensions

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#73]
The old Extensions for Calliope Mini like RGB-Colorsensor or calliope BC95 are missing. The Grove Extension v0.1.5 is outdated (v0.1.7).
The Servo Extension would be nice, too.

**Comment by Amerlander** [comment]
Servo extension is added, groove will be updated, but that has to be done in the extensions repo.

The  RGB-Colorsensor and BC95 Extensions doesnt seem to work and I think if they do not get an update they'll stay out. But you can ping @joernalraun if you think they are important and discuss this with him.

**Comment by Amerlander** [comment]
Grove is updated now

**Comment by MKleinSB** [comment]
BC95 works here:
https://github.com/MKleinSB/pxt-bc95

**Comment by MKleinSB** [comment]
sorry, does not work, but is not necessary
