### ISSUE TITLE
Feature Request: add loudness for the microphone in Simulator and Input

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#74]
Circuit playground has a microphone, too. You can change the value for loudness in the simulator like the lightlevel or temperature. So it would be nice to have this for Calliope Mini!

![Unbenannt](https://user-images.githubusercontent.com/37311672/72839675-016cfb80-3c93-11ea-989a-27b2bc797c0a.png)

And the way to read the values of the microphone is a little bit difficult/inkonsequent for children. You know Calliope Mini is designed for Children at the age of 9 years. So it would be better to add a loudness Block in Input instead of reading an analog Pin and search the Button for the microphone.

![Unbenannt2](https://user-images.githubusercontent.com/37311672/72839697-0a5dcd00-3c93-11ea-9d23-9ef04c794508.png)

Thanks! Michael

**Comment by MKleinSB** [comment]
This is the needed Code in DAL. Loudness will be from 0 to 100
https://forum.calliope.cc/t/mikrofon-empfindlichkeit/842/13

**Comment by Amerlander** [comment]
Thank you, haven't had a look yet, but the enhancing the simulator will be the next thing I do.

If you are working on the code, you can feel free to make changes in this repo (or the one which is hosted in github.org/calliope-edu) and create pull requests.

**Comment by MKleinSB** [comment]
Hm, this:
https://github.com/OpenRoberta/microbit-dal/blob/e986dbcae07cf0d76a7ad67050890e1a5a723485/source/drivers/MicroBitPin.cpp#L298
is missing in **your** DAL as far as I see. It only needs to be copied and exposed in basic.cpp to be used as a block. But I´m not a programmer you know ;-)

**Comment by Amerlander** [comment]
Me neither, I've studied something different ;)

There is one already working on the dal, so I ask him first if he already integrates it. If not I will change this.

**Comment by MKleinSB** [comment]
If not, use my translated code https://github.com/MKleinSB/pxt-mikrofon . Perhaps the easy way.

**Comment by Amerlander** [comment]
Targeted in https://github.com/microsoft/pxt-calliope/pull/147

**Comment by MKleinSB** [comment]
Hm, I cannot find the three standard functions onLoudSound(), soundLevel() and setLoudSoundThreshold() in your latest beta?
