### ISSUE TITLE
"more" submenu in blocks menu not longer working (in beta)

### ISSUE THREAD

**Issue by MarkusPiotrowski** [microsoft/pxt-calliope#77]
makecode.calliope.cc Version:  2.1.45
Microsoft MakeCode Version:  5.32.21
Laufzeitumgebung calliope Version:  pxtgc-0

**Describe the bug**
The submenu "...more" (...mehr) in the blocks menu is not working any longer. The presented blocks stay the same. So you cannot access the additional blocks.

**To Reproduce**
1. Go to https://makecode.calliope.cc/beta#editor
2. Click on e.g. 'Eingabe' (input blocks are shown)
3. Click on '...mehr' (blocks don't change)

**Expected behavior**
Clicking on a '...more' submenu should show the additional blocks.

**Screenshots**

![grafik](https://user-images.githubusercontent.com/4503120/73766270-15762a00-4776-11ea-8f2d-ac08c6c8703d.png)

![grafik](https://user-images.githubusercontent.com/4503120/73766380-39397000-4776-11ea-930d-10596bec8740.png)

**Desktop (please complete the following information):**
 - OS: Win7 Prof.
 - Browser: Firefox
 - Version: 72.0.2 (64 bit)

**Comment by MKleinSB** [comment]
https://github.com/microsoft/pxt-microbit/issues/2594

**Comment by MarkusPiotrowski** [comment]
"Doppelt hält besser" ;-) 

Sorry, I didn't see that one. Always hard to know the correct repository...

**Comment by MKleinSB** [comment]
Du warst schon richtig, aber beim microbit schauen mehr Microsoftmitarbeiter vorbei ;)

**Comment by pelikhan** [comment]
Fixed now.
