### ISSUE TITLE
Badly chosen color in advanced Mode

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#80]
Not really a bug but the color on advanced is badly chosen for easy reading.
Or am I just getting old?

![Unbenannt](https://user-images.githubusercontent.com/37311672/74263911-07895180-4d00-11ea-9380-b19c5255b138.png)

**Comment by joernalraun** [comment]
You are getting old! :)
It has been integrated by mistake and should be fixed within the next update(s)!
