### ISSUE TITLE
Error in simulator

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#84]
Hm, show number doesn´t work any more in simulator. Only LED(0/0) is blinking

![grafik](https://user-images.githubusercontent.com/37311672/74562552-60a8ed80-4f6b-11ea-8b73-29f957830b3c.png)

**Comment by MKleinSB** [comment]
Showtext ebenso

**Comment by Amerlander** [comment]
the whole display is broken, will be fixed with https://github.com/microsoft/pxt-calliope/pull/85

**Comment by pelikhan** [comment]
Fixes deployed.
