### ISSUE TITLE
Error: This project is already opened elsewhere

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#86]
When I try to delete files sometimes the errormessage **This project is already opened elsewhere** appears. But it isn´t opened elsewhere.

![Unbenannt](https://user-images.githubusercontent.com/37311672/74609226-61b35980-50e8-11ea-8be0-0089a8ef3d3e.png)

**Comment by pelikhan** [comment]
Yes that is a regression.

**Comment by pelikhan** [comment]
should be fixed
