### ISSUE TITLE
Cannot access to old github repositories

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#87]
Makecode doesn´t list my old repositories any more if I use my developer token. I only can create new ones.

![Unbenannt](https://user-images.githubusercontent.com/37311672/74643066-69204480-5174-11ea-9936-ae36c4cb01c0.jpg)

**Comment by pelikhan** [comment]
Use import url for now. The query for repoes is being more precise which may cause problems.

**Comment by pelikhan** [comment]
should be fixed.
