### ISSUE TITLE
Blocks ghosted in Tutorials

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#92]
**Describe the bug**
sometimes Blocks are ghosted in Tutorials
(On microbit it works)

**To Reproduce**
https://makecode.calliope.cc/beta/#tutorial:https://github.com/MKleinSB/pxt-crashybird-deutsch
go to step 6 and klick hint

![Unbenannt](https://user-images.githubusercontent.com/37311672/77246122-5d68e780-6c24-11ea-80de-91d2e9b95279.png)

**Comment by pelikhan** [comment]
Turn this flag off: https://github.com/microsoft/pxt-calliope/blob/master/pxtarget.json#L424

**Comment by MKleinSB** [comment]
Thanks pelikhan! @Amerlander can you please do this?
