### ISSUE TITLE
percent sign missing in "motors"

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#93]
There should be a "%" sign at the end of the motorstrings.

![Unbenannt](https://user-images.githubusercontent.com/37311672/78109278-3024f200-73f9-11ea-9c69-094df802795d.png)

**Comment by joernalraun** [comment]
This should be done within Crowdin – I think. I added the percentage symbol there.

**Comment by MKleinSB** [comment]
Thanks, but the english strings must be changed, too.

**Comment by MKleinSB** [comment]
Hm, you can add % but it never appears. Perhaps the wrapper eats it. He thinks it´s a Variable.

**Comment by joernalraun** [comment]
Maybe, I copied from another string. I could see that you added it somewhere a while ago. However, I put it in a different field where it wasn't included.

**Comment by MKleinSB** [comment]
I found the solution. I had to use backslash \%

**Comment by MKleinSB** [comment]
Ah, should be added in the english source strings, too.
