### ISSUE TITLE
Bad colors in seriell

### ISSUE THREAD

**Issue by MKleinSB** [microsoft/pxt-calliope#99]
Please change the colors for the pins in seriell to white instead of black.
Just see, it´s in all gridpickers. Wasn´t this fixed in makecode for microbit yet? 
![Unbenannt](https://user-images.githubusercontent.com/37311672/80873192-27a12f00-8cb7-11ea-8b2c-f74525ce6776.png)

**Comment by pelikhan** [comment]
We have fixed this in the latest pxt
